dist: trusty
language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

virtualenv:
  system_site_packages: true

branches:
  only:
  - master
  - staging

notifications:
  email:
    recipients:
      - chief@google.com
  on_failure: always

before_install:

    # Install Bazel
  - wget https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel_0.23.2-linux-x86_64.deb
  - echo 0823fc99462f877c34753907a328d61fefc881c9859a3438fd26762d826a1dc7 bazel_0.23.2-linux-x86_64.deb | sha256sum -c -
  - sudo dpkg -i bazel_0.23.2-linux-x86_64.deb
  - rm bazel_0.23.2-linux-x86_64.deb

    # Install App Engine test dependency
  - pip install Pillow

# Shard test execution to avoid Bazel failing with OOM/OOS on the Travis VM.
# Without sharding, failure occurred after ~25 tests.
script: "./run_tests.sh $GROUP $TOTAL_GROUPS"
env:
    global:
        - TOTAL_GROUPS=4
    matrix:
        - GROUP=0
        - GROUP=1
        - GROUP=2
        - GROUP=3
